window.FULL_LESSONS = window.FULL_LESSONS || {};
window.FULL_LESSONS["day-06-cicd"] = {
  "day": 6,
  "title": "CI/CD",
  "subtitle": "A controlled path from code to production through verification, immutable artifacts, deployment, and recovery.",
  "tags": [
    "CI/CD",
    "Immutable artifacts",
    "Canary",
    "Database migrations",
    "OIDC",
    "Rollback"
  ],
  "core": "A good CI/CD system does not merely automate deployments. It creates a controlled, repeatable path by which every production change can be built, verified, traced, released, and—when necessary—reversed.",
  "sections": [
    {
      "title": "Overview",
      "diagram": "flowchart LR\n  PR[Pull request] --> Verify[Build / test / scan]\n  Verify --> Artifact[Immutable artifact]\n  Artifact --> Stage[Staging]\n  Stage --> Prod[Canary / blue-green]\n  Prod --> Observe[Technical + business verification]\n  Observe -- abort / rollback --> Prod",
      "body": "<p>A useful mental model:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Source code\n    ↓\nContinuous Integration\n    ↓\nTrusted immutable artifact\n    ↓\nContinuous Delivery/Deployment\n    ↓\nProduction\n    ↓\nVerification and recovery\n</code></pre></div>"
    },
    {
      "title": "1. What CI and CD Mean",
      "diagram": null,
      "body": "<h5>Continuous Integration</h5>\n<p>Developers merge small changes frequently. Every change is automatically:</p>\n<ul>\n<li>compiled</li>\n<li>tested</li>\n<li>statically analyzed</li>\n<li>security-scanned</li>\n<li>packaged</li>\n</ul>\n<p>CI answers:</p>\n<div class=\"callout\">\n<p>Is this commit safe enough to become a release candidate?</p>\n</div>\n<h5>Continuous Delivery</h5>\n<p>Every successful change is automatically prepared for deployment, but production deployment requires approval.</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Commit → Build → Test → Stage → Approval → Production\n</code></pre></div>\n<h5>Continuous Deployment</h5>\n<p>Every change that passes the pipeline is deployed automatically.</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Commit → Build → Test → Stage → Production\n</code></pre></div>\n<p>Continuous deployment demands excellent automated testing, observability, feature flags, and rollback mechanisms. Many regulated or payment systems deliberately use continuous delivery instead.</p>"
    },
    {
      "title": "2. A Production Pipeline",
      "diagram": null,
      "body": "<p>For a Spring Boot service:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Pull request\n    ↓\nCompile and unit tests\n    ↓\nStatic analysis and dependency scan\n    ↓\nMerge to main\n    ↓\nBuild JAR/container once\n    ↓\nPublish artifact\n    ↓\nDeploy to development\n    ↓\nIntegration and contract tests\n    ↓\nDeploy to staging\n    ↓\nSmoke/performance/security tests\n    ↓\nApproval\n    ↓\nDeploy to production\n    ↓\nPost-deployment verification\n</code></pre></div>\n<p>The most important rule is:</p>\n<div class=\"callout\">\n<p>Build once, promote the same artifact through every environment.</p>\n</div>\n<p>Do not compile separate binaries for development, staging, and production. Otherwise, the artifact tested in staging is not exactly the artifact deployed to production.</p>\n<p>Environment differences should come from external configuration and secrets:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Artifact: payment-service:1.8.3\nDevelopment config: dev\nStaging config: staging\nProduction config: production\n</code></pre></div>"
    },
    {
      "title": "3. Pipeline Triggers",
      "diagram": null,
      "body": "<p>Common triggers include:</p>\n<h5>Pull request pipeline</h5>\n<p>Fast feedback:</p>\n<ul>\n<li>compilation</li>\n<li>unit tests</li>\n<li>linting</li>\n<li>static analysis</li>\n<li>changed-component tests</li>\n<li>secret scanning</li>\n</ul>\n<p>It should ideally finish within several minutes.</p>\n<h5>Main-branch pipeline</h5>\n<p>Produces the official artifact:</p>\n<ul>\n<li>repeat all critical checks</li>\n<li>assign immutable version</li>\n<li>build image</li>\n<li>generate SBOM</li>\n<li>sign artifact</li>\n<li>publish it</li>\n</ul>\n<h5>Release pipeline</h5>\n<p>Promotes an existing artifact into an environment.</p>\n<h5>Scheduled pipeline</h5>\n<p>Useful for:</p>\n<ul>\n<li>complete dependency scans</li>\n<li>long integration suites</li>\n<li>performance tests</li>\n<li>disaster-recovery validation</li>\n<li>certificate-expiry checks</li>\n</ul>\n<p>Scheduled tests supplement commit-time checks; they must not become a place to hide essential validation.</p>"
    },
    {
      "title": "4. Pipeline Stages vs Jobs",
      "diagram": null,
      "body": "<p>A stage represents a logical quality gate:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Build → Verify → Package → Deploy → Validate\n</code></pre></div>\n<p>Jobs inside a stage can often run in parallel:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>                ┌─ Unit tests\nCommit → Build ─┼─ Static analysis\n                ├─ Dependency scan\n                └─ License scan\n</code></pre></div>\n<p>Deployment begins only after every required check passes.</p>\n<p>Parallel execution reduces feedback time, but excessive fragmentation creates orchestration overhead and makes failures harder to understand.</p>"
    },
    {
      "title": "5. The Test Strategy",
      "diagram": null,
      "body": "<p>A CI/CD pipeline needs several layers of tests.</p>\n<h5>Unit tests</h5>\n<p>Fast and isolated:</p>\n<div class=\"code-block\"><span class=\"code-label\">java</span><pre><code>@Test\nvoid rejectsPaymentWhenBalanceIsInsufficient() {\n    Wallet wallet = new Wallet(new BigDecimal(\"100\"));\n\n    assertThrows(\n        InsufficientBalanceException.class,\n        () -&gt; wallet.debit(new BigDecimal(\"120\"))\n    );\n}\n</code></pre></div>\n<p>Run on every commit.</p>\n<h5>Integration tests</h5>\n<p>Test real boundaries such as:</p>\n<ul>\n<li>PostgreSQL queries</li>\n<li>Redis behavior</li>\n<li>Kafka serialization</li>\n<li>Spring Security configuration</li>\n<li>JPA mappings</li>\n</ul>\n<p>Testcontainers is valuable because it starts real disposable infrastructure rather than relying on behavioral mocks.</p>\n<h5>Contract tests</h5>\n<p>Verify that independently deployed services agree on request and response formats.</p>\n<p>They catch situations such as:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Provider renamed customerId to userId\nConsumer still expects customerId\n</code></pre></div>\n<h5>End-to-end tests</h5>\n<p>Validate a few critical user journeys:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Login → Create order → Pay → Receive confirmation\n</code></pre></div>\n<p>They are valuable but slower and more fragile. Do not attempt to express every business rule through browser-based tests.</p>\n<h5>Smoke tests</h5>\n<p>Immediately after deployment, verify essential behavior:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>GET /health/readiness\nGET /api/version\nSynthetic login\nSafe read operation\n</code></pre></div>\n<p>For a payment system, avoid a smoke test that creates real financial effects unless a dedicated synthetic account and reversal procedure exist.</p>"
    },
    {
      "title": "6. Quality Gates",
      "diagram": null,
      "body": "<p>A quality gate determines whether an artifact can move forward.</p>\n<p>Examples:</p>\n<ul>\n<li>build succeeds</li>\n<li>required tests pass</li>\n<li>no critical known vulnerability</li>\n<li>code coverage does not regress beyond policy</li>\n<li>API contracts remain compatible</li>\n<li>artifact signature is valid</li>\n<li>required approval exists</li>\n<li>staging smoke tests pass</li>\n</ul>\n<p>A gate should be deterministic. A flaky test is not merely inconvenient—it weakens the organization’s trust in the entire delivery system.</p>\n<p>If developers regularly rerun failed pipelines until they pass, the pipeline has stopped functioning as a safety mechanism.</p>"
    },
    {
      "title": "7. Artifact Management",
      "diagram": null,
      "body": "<p>Release artifacts include:</p>\n<ul>\n<li>JAR or WAR files</li>\n<li>Docker images</li>\n<li>Helm charts</li>\n<li>Lambda packages</li>\n<li>database migration files</li>\n<li>infrastructure plans</li>\n</ul>\n<p>Artifacts should be:</p>\n<ul>\n<li>immutable</li>\n<li>uniquely versioned</li>\n<li>traceable to a Git commit</li>\n<li>checksummed or signed</li>\n<li>retained according to recovery requirements</li>\n</ul>\n<p>Good identifiers:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>payment-service:2.4.1\npayment-service:2.4.1+git.8fa712c\npayment-service@sha256:abc123...\n</code></pre></div>\n<p>Risky identifier:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>payment-service:latest\n</code></pre></div>\n<p><code class=\"inline-code\">latest</code> is mutable and does not identify what is running. Deploy using a version or image digest.</p>\n<p>A useful production metadata endpoint might return:</p>\n<div class=\"code-block\"><span class=\"code-label\">json</span><pre><code>{\n  \"version\": \"2.4.1\",\n  \"gitCommit\": \"8fa712c\",\n  \"buildTime\": \"2026-07-10T02:28:00Z\"\n}\n</code></pre></div>\n<p>Do not expose sensitive pipeline or repository information through it.</p>"
    },
    {
      "title": "8. Configuration and Secrets",
      "diagram": null,
      "body": "<p>Never bake production secrets into an image, source repository, or pipeline log.</p>\n<p>Prefer:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Application artifact\n    +\nRuntime configuration\n    +\nSecret reference\n</code></pre></div>\n<p>Secrets may come from:</p>\n<ul>\n<li>AWS Secrets Manager</li>\n<li>AWS Systems Manager Parameter Store</li>\n<li>HashiCorp Vault</li>\n<li>Kubernetes Secrets with an appropriate encryption strategy</li>\n</ul>\n<p>The deployment identity should retrieve only the secrets needed for that environment.</p>\n<p>Avoid passing secrets through command-line arguments because process listings and debug output may expose them.</p>"
    },
    {
      "title": "9. Pipeline Security",
      "diagram": null,
      "body": "<p>A CI/CD platform is effectively a privileged production administration system. Compromising it can allow an attacker to ship malicious code.</p>\n<p>Important protections:</p>\n<ul>\n<li>protected main and release branches</li>\n<li>mandatory reviews</li>\n<li>short-lived credentials</li>\n<li>least-privilege deployment roles</li>\n<li>environment-specific roles</li>\n<li>signed commits or artifacts where justified</li>\n<li>dependency pinning</li>\n<li>secret scanning</li>\n<li>isolated untrusted pull-request execution</li>\n<li>restricted production approvals</li>\n<li>tamper-resistant audit logs</li>\n</ul>\n<p>For GitHub Actions on AWS, OIDC is generally preferable to long-lived AWS access keys:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>GitHub Actions\n    ↓ OIDC identity token\nAWS STS\n    ↓ temporary credentials\nDeployment role\n</code></pre></div>\n<p>The role’s trust policy should constrain, as appropriate:</p>\n<ul>\n<li>GitHub organization</li>\n<li>repository</li>\n<li>branch or environment</li>\n<li>workflow identity</li>\n<li>audience</li>\n</ul>\n<p>Do not let every branch in every repository assume the production role.</p>\n<p>Third-party pipeline actions are executable dependencies. Pinning only to a movable tag such as <code class=\"inline-code\">@v4</code> carries supply-chain risk; high-assurance pipelines can pin actions to reviewed commit SHAs.</p>"
    },
    {
      "title": "10. Build Reproducibility",
      "diagram": null,
      "body": "<p>Two builds of the same source should ideally produce functionally identical artifacts.</p>\n<p>Sources of non-reproducibility include:</p>\n<ul>\n<li>unpinned dependency versions</li>\n<li>downloading “latest”</li>\n<li>mutable base-image tags</li>\n<li>timestamps embedded in output</li>\n<li>environment-dependent build steps</li>\n<li>undeclared build tools</li>\n</ul>\n<p>Pin:</p>\n<ul>\n<li>JDK version</li>\n<li>Maven/Gradle version</li>\n<li>dependency versions</li>\n<li>build image</li>\n<li>Docker base-image digest when assurance requirements justify it</li>\n</ul>\n<p>Dependency caching can speed up builds, but cache keys should include relevant lockfiles and build definitions. Never allow an untrusted branch to poison a cache later consumed by privileged release jobs.</p>"
    },
    {
      "title": "11. Database Migrations",
      "diagram": null,
      "body": "<p>Database changes are one of the hardest CI/CD problems because application rollback does not automatically roll back data.</p>\n<p>A dangerous deployment:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>1. Rename database column\n2. Deploy new application\n3. Old instances continue running\n4. Old instances fail\n</code></pre></div>\n<p>During rolling deployment, old and new versions coexist. Schema changes must temporarily support both.</p>\n<p>Use the expand-and-contract pattern.</p>\n<h5>Release A: Expand</h5>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Add new column\nKeep old column\nApplication understands both\nOptionally dual-write\n</code></pre></div>\n<h5>Migration phase</h5>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Backfill new column in controlled batches\nValidate completeness\nMonitor load and replication lag\n</code></pre></div>\n<h5>Release B: Switch</h5>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Read from new column\nRetain compatibility temporarily\n</code></pre></div>\n<h5>Release C: Contract</h5>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Stop writing old column\nRemove old column after rollback window\n</code></pre></div>\n<p>Avoid combining a destructive migration and code dependency on that migration in the same immediate release.</p>\n<p>For large tables, consider:</p>\n<ul>\n<li>whether the DDL takes an exclusive lock</li>\n<li>transaction-log growth</li>\n<li>replica lag</li>\n<li>backfill throttling</li>\n<li>migration resumability</li>\n<li>remaining disk capacity</li>\n<li>rollback or forward-fix strategy</li>\n</ul>\n<p>Production migration execution should be controlled so that multiple application instances do not race to run the same migration.</p>"
    },
    {
      "title": "12. Deployment Strategies",
      "diagram": null,
      "body": "<h5>Recreate</h5>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Stop old → Deploy new → Start new\n</code></pre></div>\n<p>Simple, but causes downtime.</p>\n<h5>Rolling deployment</h5>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Old Old Old\nNew Old Old\nNew New Old\nNew New New\n</code></pre></div>\n<p>Efficient and commonly used, but old and new versions coexist. APIs and schemas must remain compatible.</p>\n<h5>Blue-green deployment</h5>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Blue: current production\nGreen: new version\n</code></pre></div>\n<p>Test green, then switch traffic. Rollback is fast if blue remains viable.</p>\n<p>Trade-off: temporarily requires roughly twice the application capacity, and database changes still require compatibility.</p>\n<h5>Canary release</h5>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>1% → 5% → 25% → 50% → 100%\n</code></pre></div>\n<p>Observe errors, latency, and business metrics at each stage. A canary is useful only if you can compare it against the baseline and abort automatically.</p>\n<h5>Feature flags</h5>\n<p>Deploy code without enabling behavior:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Deploy dormant feature\n    ↓\nEnable for employees\n    ↓\nEnable for 1%\n    ↓\nIncrease gradually\n</code></pre></div>\n<p>Feature release and code deployment become separate decisions. Flags require ownership and expiry dates; otherwise they accumulate into permanent branching complexity.</p>"
    },
    {
      "title": "13. Graceful Deployment of Spring Services",
      "diagram": null,
      "body": "<p>Before stopping an instance:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Mark instance unready\n    ↓\nLoad balancer stops new traffic\n    ↓\nDrain in-flight requests\n    ↓\nStop message consumption\n    ↓\nFinish or safely abandon work\n    ↓\nClose resources\n    ↓\nTerminate process\n</code></pre></div>\n<p>A robust service needs:</p>\n<ul>\n<li>a meaningful readiness endpoint</li>\n<li>graceful JVM shutdown</li>\n<li>a sufficient load-balancer deregistration delay</li>\n<li>bounded request durations</li>\n<li>correct handling of termination signals</li>\n<li>idempotent message processing</li>\n</ul>\n<p>For asynchronous consumers, removing HTTP traffic is not enough. The service must also stop polling queues and correctly commit or release in-flight messages.</p>\n<p>For WebSockets, deployment may require:</p>\n<ul>\n<li>connection draining</li>\n<li>server-initiated reconnect</li>\n<li>client retry with randomized delay</li>\n<li>externalized session state</li>\n<li>sufficient overlap between versions</li>\n</ul>"
    },
    {
      "title": "14. Rollback Is Not Always Reversal",
      "diagram": null,
      "body": "<p>A rollback works when the previous application remains compatible with the current database and external state.</p>\n<p>It may be unsafe after:</p>\n<ul>\n<li>destructive schema changes</li>\n<li>irreversible data transformations</li>\n<li>messages published in a new format</li>\n<li>externally visible side effects</li>\n<li>new encryption or serialization formats</li>\n<li>changes to third-party integrations</li>\n</ul>\n<p>Sometimes the correct recovery is a forward fix:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Bad v2\n    ↓\nDeploy corrected v3\n</code></pre></div>\n<p>Every release should answer before deployment:</p>\n<ol>\n<li>Can the application be rolled back?</li>\n<li>Is the database backward-compatible?</li>\n<li>Can consumers understand newly published messages?</li>\n<li>What irreversible effects can occur?</li>\n<li>What signal triggers an abort?</li>\n</ol>"
    },
    {
      "title": "15. Post-Deployment Verification",
      "diagram": null,
      "body": "<p>A deployment is not successful merely because the orchestrator reports success.</p>\n<p>Verify:</p>\n<h5>Technical signals</h5>\n<ul>\n<li>readiness</li>\n<li>HTTP 5xx rate</li>\n<li>timeout rate</li>\n<li>P95 and P99 latency</li>\n<li>CPU and memory</li>\n<li>thread and connection pools</li>\n<li>database error rate</li>\n<li>queue lag</li>\n<li>restart count</li>\n</ul>\n<h5>Business signals</h5>\n<ul>\n<li>payment authorization success</li>\n<li>login success</li>\n<li>order completion</li>\n<li>message delivery</li>\n<li>submission completion</li>\n</ul>\n<p>A service can return HTTP 200 while producing incorrect business results. Business metrics help detect “technically healthy but functionally broken” releases.</p>"
    },
    {
      "title": "16. Automated Rollback",
      "diagram": null,
      "body": "<p>A canary policy might say:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Rollback when, for five consecutive minutes:\n\n5xx rate &gt; baseline + 1%\nOR\nP99 latency &gt; baseline × 1.5\nOR\npayment success rate drops by 2%\n</code></pre></div>\n<p>Use multiple signals and minimum traffic thresholds. With only ten canary requests, one failure produces a misleading 10% error rate.</p>\n<p>Also distinguish:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Canary-specific problem\n</code></pre></div>\n<p>from:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>External dependency outage affecting every version\n</code></pre></div>\n<p>Rolling back during a database or payment-provider outage may accomplish nothing.</p>"
    },
    {
      "title": "17. Deployment Concurrency",
      "diagram": null,
      "body": "<p>Two production deployments running simultaneously can interfere:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Pipeline A deploys version 10\nPipeline B deploys version 11\nPipeline A completes later and overwrites version 11\n</code></pre></div>\n<p>Use environment-level concurrency controls:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Only one production deployment at a time\n</code></pre></div>\n<p>Superseding a pending deployment can be safe, but cancelling a deployment already performing a database migration may be dangerous. Cancellation behavior must be designed explicitly.</p>"
    },
    {
      "title": "18. Monorepos and Selective Builds",
      "diagram": null,
      "body": "<p>A monorepo may contain:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>user-service\nwallet-service\npayment-service\nfrontend\ninfrastructure\n</code></pre></div>\n<p>Rebuilding everything for every commit is simple but expensive.</p>\n<p>Selective pipelines determine affected components from:</p>\n<ul>\n<li>changed paths</li>\n<li>dependency graphs</li>\n<li>shared-library changes</li>\n</ul>\n<p>A shared library change may require testing many services, even if their directories were untouched. Path filtering alone can miss transitive impact.</p>"
    },
    {
      "title": "19. Infrastructure Changes in CI/CD",
      "diagram": null,
      "body": "<p>Infrastructure should follow a reviewable lifecycle:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Terraform validate\n    ↓\nSecurity/policy scan\n    ↓\nTerraform plan\n    ↓\nHuman review for sensitive environments\n    ↓\nApply reviewed plan\n    ↓\nValidate infrastructure\n</code></pre></div>\n<p>Important questions:</p>\n<ul>\n<li>Does this replace a database?</li>\n<li>Does it remove a security-group rule?</li>\n<li>Does it expose a public endpoint?</li>\n<li>Does it modify IAM trust?</li>\n<li>Does it destroy persistent data?</li>\n<li>Has the plan changed since approval?</li>\n</ul>\n<p>Applying a newly generated plan after someone approved an older plan defeats the approval.</p>"
    },
    {
      "title": "20. A Practical GitHub Actions Shape",
      "diagram": null,
      "body": "<div class=\"code-block\"><span class=\"code-label\">yaml</span><pre><code>name: payment-service-ci\n\non:\n  pull_request:\n  push:\n    branches: [main]\n\npermissions:\n  contents: read\n\njobs:\n  verify:\n    runs-on: ubuntu-latest\n\n    steps:\n      - name: Check out source\n        uses: actions/checkout@v4\n\n      - name: Configure Java\n        uses: actions/setup-java@v4\n        with:\n          distribution: corretto\n          java-version: \"17\"\n          cache: maven\n\n      - name: Verify application\n        run: ./mvnw --batch-mode clean verify\n</code></pre></div>\n<p>The release workflow would then:</p>\n<ol>\n<li>build the artifact once</li>\n<li>publish it with an immutable version</li>\n<li>authenticate to AWS through OIDC</li>\n<li>deploy that version to staging</li>\n<li>verify staging</li>\n<li>obtain production approval</li>\n<li>promote the exact same version</li>\n<li>verify production</li>\n</ol>\n<p>The production job should declare only the permissions it needs; repository-wide write permissions are rarely appropriate.</p>"
    },
    {
      "title": "21. Common Production Mistakes",
      "diagram": null,
      "body": "<h5>Rebuilding per environment</h5>\n<p>Staging validates one artifact, while production receives another.</p>\n<h5>Deploying mutable tags</h5>\n<p><code class=\"inline-code\">latest</code> can silently point to a different image during rollback or autoscaling.</p>\n<h5>Sharing credentials across environments</h5>\n<p>A compromised development job gains production access.</p>\n<h5>Performing destructive schema changes immediately</h5>\n<p>Old application instances and rollback versions stop working.</p>\n<h5>Treating deployment success as service health</h5>\n<p>The process is running, but requests or business transactions are failing.</p>\n<h5>Logging secrets</h5>\n<p>Shell tracing, environment dumps, generated configuration, and exception messages can leak credentials.</p>\n<h5>Ignoring pipeline failure modes</h5>\n<p>What happens if the runner dies halfway through a migration or traffic switch?</p>\n<h5>Excessive manual steps</h5>\n<p>Manual commands create drift and make recovery difficult to reproduce.</p>\n<h5>One enormous pipeline</h5>\n<p>Unrelated services block one another, feedback becomes slow, and ownership becomes unclear.</p>"
    },
    {
      "title": "22. Interview-Style Design Answer",
      "diagram": null,
      "body": "<p><strong>Question:</strong> Design CI/CD for a Spring Boot payment service running on AWS.</p>\n<p>A strong answer:</p>\n<div class=\"callout\">\n<p>Pull requests run compilation, unit tests, integration tests using disposable infrastructure, static analysis, dependency scanning, and contract verification. After merge, the pipeline builds one immutable container image, generates provenance and an SBOM, and publishes the image under a version and digest. The same image is promoted through development, staging, and production using externalized configuration and environment-specific secrets.</p>\n<p>GitHub Actions uses OIDC to obtain short-lived AWS credentials from environment-specific least-privilege roles. Production requires approval and uses a canary or blue-green deployment. Database changes follow expand-and-contract so old and new application versions can coexist. Readiness checks and connection draining provide graceful replacement. Post-deployment verification evaluates error rate, tail latency, resource saturation, and payment success rate. The deployment automatically aborts or rolls back when defined thresholds fail, provided the previous version remains schema-compatible; otherwise, the documented recovery path is a forward fix.</p>\n</div>"
    },
    {
      "title": "23. Practical Exercise",
      "diagram": null,
      "body": "<p>Design a pipeline for your kind of legacy Spring application:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Java 17\nSpring Framework 6\nTomcat WAR\nNGINX on EC2\nMySQL and MongoDB\nGitHub Actions\nDevelopment, staging, production\n</code></pre></div>\n<p>Decide:</p>\n<ol>\n<li>Which checks run for every pull request?</li>\n<li>Should the pipeline build a WAR once or rebuild for every environment?</li>\n<li>Where will the WAR be stored?</li>\n<li>How will each environment obtain configuration and secrets?</li>\n<li>How will GitHub Actions authenticate to AWS?</li>\n<li>How will the deployment drain traffic before restarting Tomcat?</li>\n<li>How will database migrations remain compatible with the previous WAR?</li>\n<li>What production approval is required?</li>\n<li>Which technical and business smoke tests run after deployment?</li>\n<li>Under what conditions will the system roll back?</li>\n<li>How will you prove which Git commit is running on each EC2 instance?</li>\n<li>What happens if the workflow fails after updating half the instances?</li>\n</ol>\n<p>A particularly useful extension is to design the deployment as a small state machine:</p>\n<div class=\"code-block\"><span class=\"code-label\">text</span><pre><code>Validate\n   ↓\nBuild\n   ↓\nDeploy first instance\n   ↓\nVerify canary\n   ├─ Failure → Restore previous version\n   ↓ Success\nDeploy remaining instanc\n\n&gt; Extraction note: this chapter came from a ChatGPT reader page capped at 20,000 characters. It may need a later full-export verification pass.\n</code></pre></div>"
    }
  ],
  "keyTakeaways": [
    "Build once and promote the exact immutable artifact through every environment.",
    "Treat the delivery system and its credentials as privileged production infrastructure.",
    "Use backward-compatible database changes during rolling deployment.",
    "A deployment is complete only after technical and business verification.",
    "Plan rollback, forward-fix, cancellation, and partial-deployment recovery before release."
  ]
};
